version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.12.0
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Update DEPLOY_ENV environment variable using CIRCLE_TAG
          command: |
            echo 'export DEPLOY_ENV=$(echo ${CIRCLE_TAG} | sed 's/-.*//')' >> $BASH_ENV
            source $BASH_ENV
      - run: echo $DEPLOY_ENV
      - run:
          name: Load .env based on $DEPLOY_ENV
          command: |
            if [ "$DEPLOY_ENV" = staging ]; then
              echo "" >> $(pwd)/.env
              echo "API_KEY=$API_KEY" >> $(pwd)/.env
              echo "" >> $(pwd)/.env
              echo "API_SECRET=$API_SECRET" >> $(pwd)/.env
            fi
      - run:
          name: Update Autotask
          command: |
            npm install -g defender-autotask-client
            npm run push:staging

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          context: OpenQ
          filters:
            branches:
              ignore: /.*/
            tags:
              only:
                - /^staging.*/